# Generated by Django 6.0.6 on 2026-06-03 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('system_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('ERROR', 'Erro'), ('QUESTION', 'Dúvida'), ('IMPROVEMENT', 'Melhoria')], default='ERROR', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('ANALYSIS', 'Em análise'), ('WAITING_USER', 'Aguardando usuário'), ('WAITING_THIRD_PARTY', 'Aguardando terceiro'), ('DEVELOPMENT', 'Em desenvolvimento'), ('TESTING', 'Em teste'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], default='OPEN', max_length=30)),
                ('description', models.TextField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
