# Generated by Django 6.0.5 on 2026-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='waiting_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem ao usuário'),
        ),
    ]
