# Generated by Django 6.0.5 on 2026-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketattachment_waiting_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='waiting_message',
        ),
        migrations.AddField(
            model_name='ticket',
            name='waiting_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem ao usuário'),
        ),
    ]
